"""changed transaction type deposit typo

Revision ID: 3156e4e81d17
Revises: 2dfcb9018644
Create Date: 2022-10-20 07:47:29.300410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3156e4e81d17'
down_revision = '2dfcb9018644'
branch_labels = None
depends_on = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type', existing_type=sa.ENUM('desposit', 'withdraw'), type_=sa.ENUM('deposit', 'withdrawl', 'transfer'), existing_comment='Deposit OR Withdraw')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #  op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
