"""create added timestamt to account table

Revision ID: 5de70b72fe96
Revises: af7cb6374e91
Create Date: 2022-07-30 08:09:08.459653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de70b72fe96'
down_revision = 'af7cb6374e91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False))
    op.add_column('accounts', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
