"""alter transaction type

Revision ID: 6ffdcd13f313
Revises: 7f58291ddae8
Create Date: 2022-10-20 08:27:00.367134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffdcd13f313'
down_revision = '7f58291ddae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   with op.get_context().autocommit_block():
        op.execute("ALTER TYPE transactiontype RENAME VALUE 'desposit' TO 'deposit'")

    # op.alter_column('transactions', 'transaction_type', existing_type=sa.ENUM('desposit', 'withdraw'), type_=sa.ENUM('deposit', 'withdrawl', 'transfer'), existing_comment='Deposit OR Withdraw')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
