"""changed transaction type deposit typo

Revision ID: 7f58291ddae8
Revises: 3156e4e81d17
Create Date: 2022-10-20 08:19:10.466838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f58291ddae8'
down_revision = '3156e4e81d17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('transactions', 'transaction_type')
    # ### end Alembic commands ###
