"""update transaction

Revision ID: 9912401f2756
Revises: 653bdc5cf3ac
Create Date: 2022-10-18 13:19:51.709317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9912401f2756'
down_revision = '653bdc5cf3ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
